from building import *

cwd  = GetCurrentDir()
src  = Split('''
sunxi_gpio.c
''')
list = os.listdir(cwd)
CPPPATH = [cwd]
objs = []

if GetDepend('SOC_ALLWINNER_R528'):
    src += ['sun8i_r528_pinctrl.c'];
    src += ['sun8i_r528_clock.c'];
    src += ['sun8i_r528_gpio.c'];
    if GetDepend('RT_USING_SERIAL'):
        src += ['sun8i_r528_uart.c']

if GetDepend('RT_USING_SDIO'):
    src += ['sunxi_sdhci.c']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))
objs = objs + group

Return('objs')